### ISSUE TITLE
Macro `str_` conflicts with third party libraries

### ISSUE THREAD

**Issue by bblanchon** [RAKWireless/RAK-STM32-RUI#10]
https://github.com/RAKWireless/RAK-STM32-RUI/blob/cb8b6bd97b418c77f908e3a987b9f81d7c457733/cores/STM32WLE/component/service/mode/cli/atcmd_queue.h#L21

This macro conflicts with ArduinoJson (https://github.com/bblanchon/ArduinoJson/issues/1978).

Please use a naming convention that doesn't clash with standard C++ practices.
For example, use `ALL_CAPS`, as recommended in the [Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-ALL_CAPS).

**Comment by beegee-tokyo** [comment]
Fixed. RUI3 is now ArduinoJSON compatible
