### ISSUE TITLE
HardwareTimer request

### ISSUE THREAD

**Issue by robi772** [RAKWireless/RAK-STM32-RUI#2]
Hi,
Possible to copy from the Stm32duino the HardwareTimer function?
Thanks

**Comment by rak-kerry** [comment]
RUI has the hardware base timer APIs in deveoping (refer to below screenshot). It will release in next version. 
![image](https://user-images.githubusercontent.com/71499605/185393457-78387e89-b1d5-4277-be51-665e9d77528d.png)

**Comment by beegee-tokyo** [comment]
api.system.timer is available
