### ISSUE TITLE
Is it possible to use DAC with RAK-3172 module?

### ISSUE THREAD

**Issue by happytm** [RAKWireless/RAK-STM32-RUI#7]
Is it possible to use DAC (digital to analog converter) with RAK-3172 module usin pin number PA10? If So how to do it?

Thanks.

**Comment by beegee-tokyo** [comment]
PA10 is used as I2C2_SDA, but if you do not initialize the second I2C bus, `analogRead(PA10);` should work.

**Comment by happytm** [comment]
Thank you for your response.

Is it analogWrite(PA10) or analogRead(PA10)?

**Comment by happytm** [comment]
OK. Thank you.
