### ISSUE TITLE
Use of EEPROM (?)

### ISSUE THREAD

**Issue by LasaleFamine** [RAKWireless/RAK-STM32-RUI#9]
I'm trying to test the RAK3172 right now and I'm wondering if it is possible to use some sort of EEPROM. I see that the standard library from Arduino seems not to be included as I cannot compile it. Do you have any suggestion? 

Sorry if this is not the correct repository to ask this. Please redirect me to the correct one if needed.

**Comment by beegee-tokyo** [comment]
@LasaleFamine 
Our [forum](https://forum.rakwireless.com/c/lpwan-modules-evb/rak3172/92) is a better place to ask that question.
